print("lol")
#kek
#hmsdffdgdsfcvbadj
#asasadfsddsdsdffsdfasdasdfghjsdfdfgasdadufdsdsuug000dsfgdfgsdb asdf000asd
#sdasddassdasdasdsdfasdasdsdf8sdfadfsfrsfsdf00hh0000fghfghfdgfh
#asdasdsdfasdfhgdfasdfsdf324wer234f0yy,
#dfg99sdfsdf0dfgsf0jk
#kllsdf
